package com.nilsson.latentnexus.domain.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.util.List;
import java.util.Map;

/**
 * Represents an AI-generated asset within the Latent Nexus system.
 * <p>
 * This entity stores comprehensive information about a generated file, serving as the
 * primary data model for all AI assets managed by the application. Each asset is
 * uniquely identified and associated with a specific {@link WorkspaceEntity},
 * enforcing multi-tenancy and data isolation.
 * </p>
 * <p>
 * Key attributes include:
 * <ul>
 *     <li>**File Details:** `filename`, `fileHash` (SHA-256 for integrity and deduplication),
 *         `storagePath` (location in S3-compatible storage), `mimeType`, and `fileSizeBytes`.</li>
 *     <li>**Image Dimensions:** `width` and `height` for visual assets.</li>
 *     <li>**Generation Metadata:** A flexible `JSONB` column (`generationMetadata`)
 *         to store arbitrary, structured data extracted from the AI generation process
 *         (e.g., prompts, seeds, sampler settings, CFG scale, steps). This allows for
 *         rich querying and analysis of AI asset provenance.</li>
 *     <li>**Vector Embedding:** A `vector(768)` column (`embedding`) to store the
 *         768-dimensional vector representation of the asset's semantic content,
 *         generated by the Gemini API. This is crucial for enabling semantic search
 *         and similarity-based retrieval of assets.</li>
 * </ul>
 * The `workspace` field establishes a many-to-one relationship with `WorkspaceEntity`,
 * ensuring that all assets belong to a logical workspace.
 * </p>
 */
@Entity
@Table(name = "assets")
public class AssetEntity extends BaseEntity {

    @Column(name = "filename", nullable = false)
    private String filename;

    @Column(name = "file_hash", nullable = false, unique = true, length = 64)
    private String fileHash;

    @Column(name = "storage_path", nullable = false)
    private String storagePath;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "workspace_id", nullable = false)
    private WorkspaceEntity workspace;

    @Column(name = "mime_type", nullable = false)
    private String mimeType;

    @Column(name = "file_size_bytes", nullable = false)
    private Long fileSizeBytes;

    @Column(name = "width")
    private Integer width;

    @Column(name = "height")
    private Integer height;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "generation_metadata", columnDefinition = "jsonb")
    private Map<String, Object> generationMetadata;

    @Column(name = "embedding", columnDefinition = "vector(768)")
    private List<Float> embedding;

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getFileHash() {
        return fileHash;
    }

    public void setFileHash(String fileHash) {
        this.fileHash = fileHash;
    }

    public String getStoragePath() {
        return storagePath;
    }

    public void setStoragePath(String storagePath) {
        this.storagePath = storagePath;
    }

    public WorkspaceEntity getWorkspace() {
        return workspace;
    }

    public void setWorkspace(WorkspaceEntity workspace) {
        this.workspace = workspace;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public Long getFileSizeBytes() {
        return fileSizeBytes;
    }

    public void setFileSizeBytes(Long fileSizeBytes) {
        this.fileSizeBytes = fileSizeBytes;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Map<String, Object> getGenerationMetadata() {
        return generationMetadata;
    }

    public void setGenerationMetadata(Map<String, Object> generationMetadata) {
        this.generationMetadata = generationMetadata;
    }

    public List<Float> getEmbedding() {
        return embedding;
    }

    public void setEmbedding(List<Float> embedding) {
        this.embedding = embedding;
    }
}
