package com.nilsson.latentnexus.service.metadata.strategy;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

/**
 * Metadata parsing strategy for NovelAI-generated images.
 * <p>
 * This strategy extracts generation parameters from the JSON structure embedded
 * in images generated by NovelAI. It maps NovelAI-specific keys (e.g., "uc" for
 * Undesired Content/Negative Prompt) to the application's standard metadata schema.
 * </p>
 */
@Service
public class NovelAIStrategy implements MetadataStrategy {

    private static final Logger log = LoggerFactory.getLogger(NovelAIStrategy.class);
    private static final ObjectMapper mapper = new ObjectMapper();

    @Override
    public Map<String, Object> parse(String text) {
        if (text == null || text.isBlank()) {
            return new HashMap<>();
        }

        Map<String, Object> results = new HashMap<>();
        try {
            JsonNode root = mapper.readTree(text);
            Iterator<Map.Entry<String, JsonNode>> fields = root.fields();
            while (fields.hasNext()) {
                Map.Entry<String, JsonNode> field = fields.next();
                extract(field.getKey(), field.getValue(), root, results);
            }
        } catch (Exception e) {
            log.error("Failed to parse NovelAI metadata block", e);
            throw new RuntimeException("System failed to parse NovelAI generation parameters from JSON block.", e);
        }
        return results;
    }

    @Override
    public void extract(String key, JsonNode value, JsonNode parentNode, Map<String, Object> results) {
        try {
            if (!value.isTextual() && !value.isNumber()) return;

            String text = value.asText().trim();
            if (text.isEmpty()) return;

            if (key.equals("prompt")) {
                if (!results.containsKey("Prompt")) {
                    results.put("Prompt", text);
                }
            } else if (key.equals("uc")) {
                results.put("Negative", text);
            } else if (key.equals("scale")) {
                results.put("CFG", value.isNumber() ? value.asDouble() : parseDoubleSafe(text));
            } else if (key.equals("steps")) {
                results.put("Steps", value.isNumber() ? value.asLong() : parseLongSafe(text));
            } else if (key.equals("seed")) {
                results.put("Seed", value.isNumber() ? value.asLong() : parseLongSafe(text));
            } else if (key.equals("sampler")) {
                results.put("Sampler", text);
            } else if (key.equals("software") && text.equalsIgnoreCase("novelai")) {
                if (!results.containsKey("Model")) {
                    results.put("Model", "NovelAI Diffusion");
                }
            }
        } catch (Exception e) {
            log.error("Error during NovelAI JSON extraction for key: {}", key, e);
        }
    }

    private Long parseLongSafe(String value) {
        try {
            return Long.parseLong(value);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private Double parseDoubleSafe(String value) {
        try {
            return Double.parseDouble(value);
        } catch (NumberFormatException e) {
            return null;
        }
    }
}
